<?php

class Bystritsky_Action_Model_Resource_Action_Collection extends Mage_Core_Model_Resource_Db_Collection_Abstract {
    protected function _construct()
    {
        $this->_init('bystritsky_action/action');
    }
/*
    protected function _afterLoad()
    {
        foreach ($this->getItems() as $item) {
            $item->_afterLoad();
        }

        return parent::_afterLoad(); // TODO: Change the autogenerated stub
    }
*/
}