<?php $actions = $this->getActionsCollection(); ?>
<div class="action-pager">
    <?= $this->getPagerHtml(); ?>
</div>
<h1>Current actions</h1>
<div class="action-actions">
    <?php foreach ($actions as $action): ?>
        <div class="action-entity">
            <div class="action-title">
                <h2><?= $action['name'] ?></h2>
            </div>
            <div class="action-image">
                <img class="action-image-200px" src="<?= $action['image'] ?>">
            </div>
            <div class="action-body">
                <div class="action-description">
                    <?= $action['description'] ?>
                </div>
                <div class="start-end">
                    <div class="action-start">
                        From: <span class="action-start-datetime"><?= $action['start_datetime'] ?></span>
                    </div>
                    <div class="action-end">
                        <?php if (!empty($action['end_datetime'])): ?>
                            To: <span class="action-end-datetime"><?= $action['end_datetime'] ?></span>
                        <?php else: ?>
                            <br>
                        <?php endif; ?>
                    </div>
                </div>
            </div>
        </div>
    <?php endforeach; ?>
</div>
<div class="action-pager">
    <?= $this->getPagerHtml(); ?>
</div>
