<?php
$actions = $this->getActionsCollection();
$helper = Mage::helper('bystritsky_action');
?>
<div class="action-pager">
    <?= $this->getPagerHtml(); ?>
</div>
<h1>Current actions</h1>
<div class="action-actions">
    <?php foreach ($actions as $action): ?>
        <div class="action-entity">
            <div class="action-title">
                <a href="<?= Mage::getUrl('*/*/view/id/' . $action['id']); ?>"><h2><?= $action['name'] ?></h2></a>
            </div>
            <?php if ($helper->getImageUrl($action['image'])): ?>
                <div class="action-image">
                    <img src="<?= $helper->getResizedImageUrl($action['image'], 200, 200); ?>">
                </div>
            <?php endif; ?>
            <div class="action-body">
                <div class="action-short-description">
                    <?= $action['short_description'] ?>
                </div>
                <div class="start-end">
                    <div class="action-start">
                        From: <span class="action-start-datetime"><?= $action['start_datetime'] ?></span>
                    </div>
                    <div class="action-end">
                        <?php if (!empty($action['end_datetime'])): ?>
                            To: <span class="action-end-datetime"><?= $action['end_datetime'] ?></span>
                        <?php else: ?>
                            <br>
                        <?php endif; ?>
                    </div>
                </div>
            </div>
        </div>
    <?php endforeach; ?>
</div>
<div class="action-pager">
    <?= $this->getPagerHtml(); ?>
</div>
