<?php
$action = $this->getAction();
$products = $this->getProductsRelatedToAction($action, [
    'visibility' => Mage_Catalog_Model_Product_Visibility::VISIBILITY_BOTH,
    'status' => Mage_Catalog_Model_Product_Status::STATUS_ENABLED
], ['name', 'sku', 'image', 'price']);
$helper = Mage::helper('bystritsky_action');
?>
<div class="action-actions">
    <div class="action-entity">
        <div class="action-title">
            <h2><?= $action['name'] ?></h2>
        </div>
        <div class="action-body">
            <div class="action-short-description">
                <?= $action['short_description'] ?>
            </div>
            <div class="action-description">
                <?php if ($url = $helper->getImageUrl($action['image'])): ?>
                    <div class="action-image">
                        <img class="action-image-view"
                             src="<?= $helper->getResizedImageUrl($action['image'], 300, 300); ?>">
                    </div>
                <?php endif; ?>
                <?= $action['description'] ?>
            </div>
            <div class="start-end">
                <div class="action-start">
                    <?= $this->__('From: '); ?><span class="action-start-datetime"><?= $action['start_datetime'] ?></span>
                </div>
                <div class="action-end">
                    <?php if (!empty($action['end_datetime'])): ?>
                        <?= $this->__('To: '); ?><span class="action-end-datetime"><?= $action['end_datetime'] ?></span>
                    <?php else: ?>
                        <br>
                    <?php endif; ?>
                </div>
            </div>
        </div>
        <?php if ($products->getSize()): ?>
            <div class="actions-related-products">
                <?= $this->__('Related products:'); ?>
                <div class="actions-products">
                    <?php foreach ($products as $product): ?>
                        <?php
                        $name = $product->getName();
                        $sku = $product->getSku();
                        $link = $product->getProductUrl();
                        $image = $product->getImageUrl();
                        $price = Mage::helper('core')->currency($product->getPrice(), true, false);
                        ?>
                        <div class="actions-product">
                            <div class="actions-product-cell"><a href="<?= $link ?>"><?= $name ?></a></div>
                            <div class="actions-product-cell"><?= $sku ?></div>
                            <div class="actions-product-cell"><a href="<?= $link ?>">
                                    <img class="actions-product-image" src="<?= $image ?>">
                                </a></div>
                            <div class="actions-product-cell"><?= $price ?></div>
                        </div>
                    <?php endforeach; ?>
                </div>
            </div>
        <?php endif; ?>
    </div>
</div>


